//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhDev.Common.Web.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormsAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsAnnotations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RhDev.Common.Web.Resources.Common.FormsAnnotations", typeof(FormsAnnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístupový token.
        /// </summary>
        public static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte typ role uživatele.
        /// </summary>
        public static string AssigningRoleTypeRequired {
            get {
                return ResourceManager.GetString("AssigningRoleTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ByPassFailure {
            get {
                return ResourceManager.GetString("ByPassFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BypassOnFailure {
            get {
                return ResourceManager.GetString("BypassOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla nesouhlasí.
        /// </summary>
        public static string ComparePasswordMatch {
            get {
                return ResourceManager.GetString("ComparePasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrďte nové heslo.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrďte heslo.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CookieExpirationinMinutes {
            get {
                return ResourceManager.GetString("CookieExpirationinMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémie Cu.
        /// </summary>
        public static string Counters_Bonus_CuValue {
            get {
                return ResourceManager.GetString("Counters_Bonus_CuValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémie Zn.
        /// </summary>
        public static string Counters_Bonus_ZnValue {
            get {
                return ResourceManager.GetString("Counters_Bonus_ZnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Counters_Common_Contacts {
            get {
                return ResourceManager.GetString("Counters_Common_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výchozí kultura.
        /// </summary>
        public static string Counters_Common_DefaultCulture {
            get {
                return ResourceManager.GetString("Counters_Common_DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximální množství na jednu fixaci.
        /// </summary>
        public static string Counters_Common_MaxAmount {
            get {
                return ResourceManager.GetString("Counters_Common_MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ cenování.
        /// </summary>
        public static string Counters_Common_PricingType {
            get {
                return ResourceManager.GetString("Counters_Common_PricingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spřízněný partner.
        /// </summary>
        public static string Counters_Common_RelatedPartner {
            get {
                return ResourceManager.GetString("Counters_Common_RelatedPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR / USD.
        /// </summary>
        public static string Counters_Fee_EurUsd {
            get {
                return ResourceManager.GetString("Counters_Fee_EurUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP / USD.
        /// </summary>
        public static string Counters_Fee_GbpUsd {
            get {
                return ResourceManager.GetString("Counters_Fee_GbpUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ fixace.
        /// </summary>
        public static string Counters_Fee_OrderType {
            get {
                return ResourceManager.GetString("Counters_Fee_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství.
        /// </summary>
        public static string Counters_FixAmount_Amount {
            get {
                return ResourceManager.GetString("Counters_FixAmount_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string Counters_LmeCost_From {
            get {
                return ResourceManager.GetString("Counters_LmeCost_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Counters_LmeCost_To {
            get {
                return ResourceManager.GetString("Counters_LmeCost_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        public static string Counters_LmeCost_Value {
            get {
                return ResourceManager.GetString("Counters_LmeCost_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string Counters_Profit_CurrencyId {
            get {
                return ResourceManager.GetString("Counters_Profit_CurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        public static string Counters_Profit_Value {
            get {
                return ResourceManager.GetString("Counters_Profit_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémie MP.
        /// </summary>
        public static string Counters_PurchaseBonus_Mp {
            get {
                return ResourceManager.GetString("Counters_PurchaseBonus_Mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prémie MTX.
        /// </summary>
        public static string Counters_PurchaseBonus_Mtx {
            get {
                return ResourceManager.GetString("Counters_PurchaseBonus_Mtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koeficient PCI.
        /// </summary>
        public static string Counters_PurchaseCoeficient_Mp {
            get {
                return ResourceManager.GetString("Counters_PurchaseCoeficient_Mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koeficient MTX FCA.
        /// </summary>
        public static string Counters_PurchaseCoeficient_Mtx {
            get {
                return ResourceManager.GetString("Counters_PurchaseCoeficient_Mtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koeficient MTX DDP.
        /// </summary>
        public static string Counters_PurchaseCoeficient_MtxDDP {
            get {
                return ResourceManager.GetString("Counters_PurchaseCoeficient_MtxDDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Counters_TransportType_Title {
            get {
                return ResourceManager.GetString("Counters_TransportType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální heslo.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zákazník.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nutné zvolit zákazníka.
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly za jménem.
        /// </summary>
        public static string DegreesAfterName {
            get {
                return ResourceManager.GetString("DegreesAfterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly před jménem.
        /// </summary>
        public static string DegreesBeforeName {
            get {
                return ResourceManager.GetString("DegreesBeforeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis dodávky.
        /// </summary>
        public static string DeliveryDescription {
            get {
                return ResourceManager.GetString("DeliveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis dodávky je povinný.
        /// </summary>
        public static string DeliveryDescriptionRequired {
            get {
                return ResourceManager.GetString("DeliveryDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín dodání.
        /// </summary>
        public static string DeliveryTo {
            get {
                return ResourceManager.GetString("DeliveryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email není ve správném tvaru.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některý email není ve správném formátu.
        /// </summary>
        public static string EmailListInvalid {
            get {
                return ResourceManager.GetString("EmailListInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při aktualizaci typu oznámení došlo k chybě, Id korelace : {0}.
        /// </summary>
        public static string FailedWhenSetNotificationSystem {
            get {
                return ResourceManager.GetString("FailedWhenSetNotificationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FixReviewPageSize {
            get {
                return ResourceManager.GetString("FixReviewPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrátor.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LimitOrderPageSize {
            get {
                return ResourceManager.GetString("LimitOrderPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splatnost dní.
        /// </summary>
        public static string MaturityInDays {
            get {
                return ResourceManager.GetString("MaturityInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalimex ID Partnera.
        /// </summary>
        public static string MetalimexPartnerId {
            get {
                return ResourceManager.GetString("MetalimexPartnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis obchodníka CZ.
        /// </summary>
        public static string NotificationSignCs {
            get {
                return ResourceManager.GetString("NotificationSignCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis obchodníka EN.
        /// </summary>
        public static string NotificationSignEn {
            get {
                return ResourceManager.GetString("NotificationSignEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ oznámení.
        /// </summary>
        public static string NotificationSystem {
            get {
                return ResourceManager.GetString("NotificationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole není ve zvoleném rozsahu {1} - {2}.
        /// </summary>
        public static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód musí obsahovat pouze číslice.
        /// </summary>
        public static string OnlyDigits {
            get {
                return ResourceManager.GetString("OnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo 2.
        /// </summary>
        public static string Password2 {
            get {
                return ResourceManager.GetString("Password2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo bylo změněno..
        /// </summary>
        public static string PasswordChangedSucc {
            get {
                return ResourceManager.GetString("PasswordChangedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je povinné u interních účtů.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je vyžadováno u nezákaznických účtů.
        /// </summary>
        public static string PasswordRequiredIfNotCustomer {
            get {
                return ResourceManager.GetString("PasswordRequiredIfNotCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo a potvrzovací heslo nesouhlasí.
        /// </summary>
        public static string PasswordsDoesNotmatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte prosím platné telefonní číslo.
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte platné telefonní číslo v mezinárodním formátu (00{{kód země}}{{telefonní číslo}}).
        /// </summary>
        public static string PhoneNumberInternational {
            get {
                return ResourceManager.GetString("PhoneNumberInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} musí být  {1} znaků dlouhý..
        /// </summary>
        public static string Pwd2FaLength {
            get {
                return ResourceManager.GetString("Pwd2FaLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID fronty.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přepracování.
        /// </summary>
        public static string Recasting {
            get {
                return ResourceManager.GetString("Recasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamatovat?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} je vyžadováno.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole je vyžadováno u uživatele typu zákazník.
        /// </summary>
        public static string RequiredIfCustomerAccount {
            get {
                return ResourceManager.GetString("RequiredIfCustomerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole je vyžadováno.
        /// </summary>
        public static string RequiredNoField {
            get {
                return ResourceManager.GetString("RequiredNoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role (Prodej).
        /// </summary>
        public static string Role_Cash {
            get {
                return ResourceManager.GetString("Role_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role (Nákup).
        /// </summary>
        public static string Role_Purchase {
            get {
                return ResourceManager.GetString("Role_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role (Obchod).
        /// </summary>
        public static string Role_Sales {
            get {
                return ResourceManager.GetString("Role_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role - Prodej.
        /// </summary>
        public static string RoleCash {
            get {
                return ResourceManager.GetString("RoleCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role - zákazník.
        /// </summary>
        public static string RoleCustomer {
            get {
                return ResourceManager.GetString("RoleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nutné zvolit alespoň jednu roli.
        /// </summary>
        public static string RoleCustomerRequired {
            get {
                return ResourceManager.GetString("RoleCustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role - interní.
        /// </summary>
        public static string RoleInternal {
            get {
                return ResourceManager.GetString("RoleInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nutné zvolit roli typu interní uživatele.
        /// </summary>
        public static string RoleInternalRequired {
            get {
                return ResourceManager.GetString("RoleInternalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role - Nákup.
        /// </summary>
        public static string RolePurchase {
            get {
                return ResourceManager.GetString("RolePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role - Obchod.
        /// </summary>
        public static string RoleSales {
            get {
                return ResourceManager.GetString("RoleSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SignoutInactivityIntervalInMinutes {
            get {
                return ResourceManager.GetString("SignoutInactivityIntervalInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SmsAddress {
            get {
                return ResourceManager.GetString("SmsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS notifikace.
        /// </summary>
        public static string SmsNotification {
            get {
                return ResourceManager.GetString("SmsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ dopravy.
        /// </summary>
        public static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwoFaCodeExpirationInSeconds {
            get {
                return ResourceManager.GetString("TwoFaCodeExpirationInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizační kód.
        /// </summary>
        public static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TwoFaMagicCode {
            get {
                return ResourceManager.GetString("TwoFaMagicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} musí být minimálně  {2} a maximálně {1} znaků dlouhé..
        /// </summary>
        public static string UserNameAtLeast {
            get {
                return ResourceManager.GetString("UserNameAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValueEmpty {
            get {
                return ResourceManager.GetString("ValueEmpty", resourceCulture);
            }
        }
    }
}
