// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RhDev.Customer.Component.Core.Impl.Data;

#nullable disable

namespace RhDev.Customer.Component.App.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240729121847_Workflow_Engine")]
    partial class Workflow_Engine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserApplicationUser", b =>
                {
                    b.Property<string>("AuthoredUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AuthoredUsersId", "ModifiedUsersId");

                    b.HasIndex("ModifiedUsersId");

                    b.ToTable("ApplicationUserApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Common.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasMaxLength(32768)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(32768)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("TableName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Configuration.ApplicationUserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Changed")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_Key")
                        .IsUnique();

                    b.ToTable("ApplicationUserSettings");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Utils.DayOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Repeat")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("DayOffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den obnovy samostatného českého státu"
                        },
                        new
                        {
                            Id = 2,
                            Day = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Svátek práce"
                        },
                        new
                        {
                            Id = 3,
                            Day = new DateTime(2022, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den vítězství"
                        },
                        new
                        {
                            Id = 5,
                            Day = new DateTime(2022, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den slovanských věrozvěstů Cyrila a Metoděje"
                        },
                        new
                        {
                            Id = 6,
                            Day = new DateTime(2022, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den upálení mistra Jana Husa"
                        },
                        new
                        {
                            Id = 7,
                            Day = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den české státnosti"
                        },
                        new
                        {
                            Id = 8,
                            Day = new DateTime(2022, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Den boje za svobodu a demokracii"
                        },
                        new
                        {
                            Id = 9,
                            Day = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "Štědrý den"
                        },
                        new
                        {
                            Id = 10,
                            Day = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "1. svátek vánoční"
                        },
                        new
                        {
                            Id = 11,
                            Day = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "2. svátek vánoční"
                        },
                        new
                        {
                            Id = 12,
                            Day = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = true,
                            Title = "2. svátek vánoční"
                        },
                        new
                        {
                            Id = 13,
                            Day = new DateTime(2023, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 14,
                            Day = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 15,
                            Day = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 16,
                            Day = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 17,
                            Day = new DateTime(2027, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 18,
                            Day = new DateTime(2028, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 19,
                            Day = new DateTime(2029, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 20,
                            Day = new DateTime(2030, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velký pátek"
                        },
                        new
                        {
                            Id = 21,
                            Day = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 22,
                            Day = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 23,
                            Day = new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 24,
                            Day = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 25,
                            Day = new DateTime(2027, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 26,
                            Day = new DateTime(2028, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 27,
                            Day = new DateTime(2029, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        },
                        new
                        {
                            Id = 28,
                            Day = new DateTime(2030, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Repeat = false,
                            Title = "Velikonoční pondělí"
                        });
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Utils.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClientAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ClientIP")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Exception")
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LogEvent")
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasMaxLength(32768)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceContext")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowDocuments");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CurrentTaskGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSystemProcessing")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RunVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("WorkflowDefinition")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("WorkflowDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowState")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("WorkflowStateSystem")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDocumentId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowInstanceHistory");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstanceSystemProcessingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Header")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Stamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowInstanceSystemProcessingInfo");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowProperties");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolvedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedTriggerCode")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskRespondeType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UserData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex(new[] { "AssignedTo" }, "IX_AssignedTo");

                    b.ToTable("WorkflowTasks");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowTransitionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromState")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Handler")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToState")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TransitionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowTransitionLogs");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowTransitionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastInitiatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<double>("RepeatCount")
                        .HasColumnType("float");

                    b.Property<string>("ResultData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double>("TranDuration")
                        .HasColumnType("float");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransitionType")
                        .HasColumnType("int");

                    b.Property<string>("Workflow")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowTransitionRequest");
                });

            modelBuilder.Entity("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RhDev.Customer.Component.Core.Impl.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ApplicationUserApplicationUser", b =>
                {
                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthoredUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUsersId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowDocument", b =>
                {
                    b.OwnsOne("RhDev.Common.Web.Core.Workflow.WorkflowDocumentIdentificator", "WorkflowDocumentIdentificator", b1 =>
                        {
                            b1.Property<int>("WorkflowDocumentId")
                                .HasColumnType("int");

                            b1.Property<int>("entityId")
                                .HasColumnType("int");

                            b1.Property<string>("typeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WorkflowDocumentId");

                            b1.ToTable("WorkflowDocuments");

                            b1.ToJson("WorkflowDocumentIdentificator");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDocumentId");
                        });

                    b.Navigation("WorkflowDocumentIdentificator")
                        .IsRequired();
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowDocument", "WorkflowDocument")
                        .WithMany("WorkflowInstances")
                        .HasForeignKey("WorkflowDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDocument");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstanceHistory", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowInstanceHistory")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstanceSystemProcessingInfo", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("SystemProcessingInfoItems")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowProperty", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowProperties")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowTask", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowTransitionLog", b =>
                {
                    b.HasOne("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("TransitionLogs")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("RhDev.Customer.Component.Core.Impl.Data.City", b =>
                {
                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", "CreatedBy")
                        .WithMany("AuthoredCities")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", "LastModifiedBy")
                        .WithMany("ModifiedCities")
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowDocument", b =>
                {
                    b.Navigation("WorkflowInstances");
                });

            modelBuilder.Entity("RhDev.Common.Web.Core.DataAccess.SQL.Repository.Entities.Workflow.WorkflowInstance", b =>
                {
                    b.Navigation("SystemProcessingInfoItems");

                    b.Navigation("Tasks");

                    b.Navigation("TransitionLogs");

                    b.Navigation("WorkflowInstanceHistory");

                    b.Navigation("WorkflowProperties");
                });

            modelBuilder.Entity("RhDev.Customer.Component.Core.Impl.Data.ApplicationUser", b =>
                {
                    b.Navigation("AuthoredCities");

                    b.Navigation("ModifiedCities");
                });
#pragma warning restore 612, 618
        }
    }
}
